development:
  adapter: postgresql
  encoding: unicode
  database: moviegems_dev
  pool: 5
  username: cnixon
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: moviegems_test
  pool: 5
  username: cnixon
  password:
